### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by batkiz** [xzhih/hexo-theme-casper#1]
首先感谢您制作了这个主题。下面是一些反馈

可否添加对以下功能的支持：
* mathjax
* 右上添加更多的联系方式（e.g. telegram, e-mail）
* 更换代码高亮使用的css

使用中发现了以下bug
* 如果文章标题过多，右侧toc无法完全显示且无法向下滚动

一些想法：
* 下方copyright可更改为类似2016-2018这种样式
* 下方footer仅显示纯文本
* 文章页面中，将标题显示在图片上，时间等则可以显示在标题下方。

**Comment by xzhih** [comment]
当初移植这个主题的时候，我自针对自己的需求来做，一切设置都尽量减少和简单，没打算加我用不上的东西，不过刚才我也看到你fork并新增了一些功能，挺好的，有需求你们自己加吧

**Comment by batkiz** [comment]
我就是个菜鸡，那个功能还是勉强才加上的:sweat_smile:。
那么请问您有没有 Hexo theme 相关的开发文档呢？我在 hexo.io 并没有找到，如果您能提供相关链接的话，非常感谢。

**Comment by xzhih** [comment]
hexo官方给了一些辅助函数基本足够了，然后渲染出来用的是模板引擎，我这里用的是swig，你可以去看看swig的文档
