### ISSUE TITLE
你好，我用了mathjax后localhost能加载，但发布到网页之后就不行了。 @batkiz @xzhih

### ISSUE THREAD

**Issue by woriazzc** [xzhih/hexo-theme-casper#13]
你好，我用了mathjax后localhost能加载，但发布到网页之后就不行了。 @batkiz @xzhih 
少了cdn的js。请问怎么解决呢？
![捕获1](https://user-images.githubusercontent.com/44539042/59826231-79272080-9368-11e9-85f4-a47919f0c31b.PNG)
![捕获](https://user-images.githubusercontent.com/44539042/59826233-7af0e400-9368-11e9-953d-c263ba88f90c.PNG)

_Originally posted by @woriazzc in https://github.com/xzhih/hexo-theme-casper/pull/2#issuecomment-503895820_

**Comment by xzhih** [comment]
你看一下浏览器console报什么错误，还有网络资源加载有什么错误

不知道你是搭建在哪里的，可能是跨域问题

**Comment by woriazzc** [comment]
谢谢，解决了，是mathjax网址没更新。
