### ISSUE TITLE
searchData.json is missing data from created pages

### ISSUE THREAD

**Issue by HetBenkt** [xzhih/hexo-theme-casper#15]
I use your theme for some time now and it works pretty smooth, but after a `hexo clean` and `hexo generate` I see that a new searchData.json is created. Only this file is missing data from the created pages. The posts are fine, but the pages data is not in there.

Is this done by design, is it a missing feature or is something done wrong on my side?
Best regards and keep up the good work!

**Comment by xzhih** [comment]
`searchData.json` is the data source for the search function，
you can edit `themes/hexo-casper/_config.yml`, to disable it

```yml
# Local Search
local_search: false
```

**Comment by HetBenkt** [comment]
It looks that I was not clear enough. I do want to use the search functionality, but "page" information is not indexed in the searchData.json where "post" information is. 
So items created with `hexo new post` are nicely indexed, but items created with `hexo new page` are not.
See for yourself as this is a 'page': http://appworks-tips.com/abbreviations/ and it will not pop-up in the search results when you search for 'abbreviations' where for example a 'post' http://appworks-tips.com/2019/07/26/011_uninstalling_appworks_the_proper_way/ can be found by searching for 'uninstalling'

**Comment by xzhih** [comment]
This is a simple search method, so you can only search for exact matches.
I can't find ‘abbreviations‘ in your `searchData.json` file.

**Comment by HetBenkt** [comment]
That was my conclusion also, but how do i get that ‘abbreviations‘ value in the searchData.json as it's not available when I re-generate my site with a `hexo clean` and `hexo generate`?

**Comment by xzhih** [comment]
You can add an 'abbreviations' tag to the `abbreviations.md`.

**Comment by HetBenkt** [comment]
Did it like this:
```
---
title: The prodigious list of AppWorks abbreviations
date: 2019-08-01 11:58:39
tags:
- AppWorks
- Abbreviations
keywords: appworks, abbreviations
categories:
- [Page]
---
```
After `hexo clean` and `hexo generate` it's still not in the searchData.json
Is it not the case that only .md files under the _posts folder are indexed as this page is outside that folder? I have an source/abbreviations/index.md which is created when i create a new 'page' instead of a new 'post'

**Comment by HetBenkt** [comment]
Ok, I did a deeper dive and in hexo-casper/scripts/index.js you loop over the posts like this ```posts.each(post => {...}```

I also want to add the page information in that loop. Something like this:
```
var pages = locals.pages.sort('-date')
if (pages) {
        pages.each(page => {
        	hexo.log.info(page.raw);
        })
    }
```

**Comment by xzhih** [comment]
Time passed too long, I forgot that local search did not import page, the code was really bad.

Yes, you can add the page  in that loop.

**Comment by HetBenkt** [comment]
Will do that for my local implementation...thx
