### ISSUE TITLE
关于首页布局的问题

### ISSUE THREAD

**Issue by nameussi** [xzhih/hexo-theme-casper#18]
- 关于首页文章每行的卡片布局，在文章足够多的情况下现在顺序是 1篇-3篇-2篇 依次循环，比如想改为从3篇开始布局，要怎么修改？
- header_image 的高度怎么修改？
实在找不到相关代码，所以想请教一下，谢谢了！

**Comment by xzhih** [comment]
这两个问题全是 CSS 的， 你按一下 F12看控制台，找到相关的 CSS，然后写一个新的放在页面底部就能覆盖了，第一个问题可能会复杂一些，要动的东西比较多

**Comment by xzhih** [comment]
第一个问题也可以修改 swig 模板来实现，在页面遍历文章的地方索引小于 2 的不加 class 或者增加一个新的 class （比如not-layout），然后再配合一下 CSS 选择器 :not(.not-layout)，这样应该就可以了

**Comment by nameussi** [comment]
听你这么一说第一个问题确实有点复杂，我先试试

**Comment by nameussi** [comment]
找到第一个问题的相关代码了，其实也不复杂，只需把`:nth-child(6n+1)`选择器中的`6n+1`改成`6n`就行了
