### ISSUE TITLE
一些问题和建议

### ISSUE THREAD

**Issue by nameussi** [xzhih/hexo-theme-casper#19]
- 在文章页无法使用搜索功能
- 另外，可否请求添加一个图集的功能，比如这个 https://github.com/miromannino/Justified-Gallery ，可以实现简单的相册效果。

**Comment by xzhih** [comment]
1. ‘在文章页无法使用搜索功能’ 这个应该是上次提交的时候出现的 bug，有空我修复一下。
2. ‘图集’ 功能我没需求，没动力去添加

**Comment by nameussi** [comment]
@xzhih 好吧图集的功能我自己看看怎么解决。

另外还想请教一下，photoswipe只能在post页有效在page页用不了吗？
我照着post里那样把下面的代码复制到page也不生效
```
{% if theme.photoswipe %}
{% include "public/photoswipe.swig" %}
{% endif %}
```

**Comment by xzhih** [comment]
> 另外还想请教一下，photoswipe只能在post页有效在page页用不了吗？
> 我照着post里那样把下面的代码复制到page也不生效

除了你上面加入的代码，
还要把 `layout/_partials/javascript.swig` 里的相册部分改成这样

```swig
{# 相册 #}
{% if (is_post() || is_page()) and theme.photoswipe %}
```

**Comment by nameussi** [comment]
@xzhih 可以了，谢谢！

**Comment by nameussi** [comment]
@xzhih PhotoSwipe显示不了图片标题，启用了caption功能也无效，请问可以自动获取图片alt为标题吗？

**Comment by xzhih** [comment]
这些功能都要写，我自己用不到，所以做这个主题的时候没写
