### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by stephenajulu** [xzhih/hexo-theme-casper#20]
Hi, how are you? Could you kindly add dark mode to this theme. It would be beneficial.

**Comment by xzhih** [comment]
Dark mode is automatic, if you are using MacOS, IOS13 or android10, the theme will turn dark according to system settings.

Just like this.

<img width="1456" alt="截屏2019-10-2521 39 44" src="https://user-images.githubusercontent.com/13920737/67575837-fb3cb100-f76f-11e9-955e-bda631e1062f.png">

<img width="1455" alt="截屏2019-10-2521 39 00" src="https://user-images.githubusercontent.com/13920737/67575778-df390f80-f76f-11e9-99c8-9610e7e0b07e.png">

**Comment by stephenajulu** [comment]
Thank you very much. What about Windows and Linux. or is it the same?
