### ISSUE TITLE
在主题文件_config配置文件 设置页脚相关备案信息无效

### ISSUE THREAD

**Issue by Leoin1** [xzhih/hexo-theme-casper#24]
在主题文件_config配置文件 设置页脚相关备案信息无效

 Footer Links
```
footer_text:
   #title: link
   苏ICP备xxxxx号: http://www.miitbeian.gov.cn
   粤公网安备xxxxxxx号: http://www.beian.gov.cn
```

是需要在主题的swig 文件配置吗？ 同时看预留了访问量的leancloud的相关接口后续主题会增加支持吗？

**Comment by xzhih** [comment]
底部的是 footer 字段啊，不是 footer_text

访问量那个没有展示出来，你可以把 `hidden="true"`去掉后展示，你可以把那里的代码放到你想要展示访问量的地方

**Comment by Leoin1** [comment]
感谢，用了接近2年的Hexo博客 特别喜欢这一款 希望长久更新 持续支持～

**Comment by liangwt** [comment]
_config.yml和readme里全都是写的footer_text，修正下吧。
