### ISSUE TITLE
想問該如何怎麼改部落格的大標題

### ISSUE THREAD

**Issue by mxair95000** [xzhih/hexo-theme-casper#26]
嗨您好！想問我該怎麼修改部落格的名字？就是案例裡面「Hexo」這行
我找了 config.yml 裡
但好像沒有 title 或 blog_name
我只有辦法可以改副標題 bio 

![0C27CA99-8388-44D4-B1F6-DC0C4FEAE320](https://user-images.githubusercontent.com/44470696/75096254-c2ef9700-55d8-11ea-8286-ff2210096432.png)

**Comment by xzhih** [comment]
這個是使用 hexo 的配置，你可以在 https://hexo.io/docs/configuration 這裏看到配置的字段
