### ISSUE TITLE
Post文章页面内的标题，正文字体大小如何调节？

### ISSUE THREAD

**Issue by shuyx** [xzhih/hexo-theme-casper#6]
我觉得每篇文章里的标题和正文文字都偏大，我想调节下大小。我对编程不是太懂，找到style.css，我以为字体大小是markdown h1，h2，h3和markdown-body的内容，尝试修改了下font：2em为1.7em之类的，好像也没有用。

另外，screen.css样式是渲染什么的？是生成html时用的么，字体大小是在这里调节的么？

找了这么多主题，还就您这个看着特别舒心，页面也漂亮，卡片式的主页也帅气，陆陆续续解决了一些小问题，非常喜欢您的主题，希望就这个问题能给出指点。

**Comment by xzhih** [comment]
调整 `style.css` 里的样式是对的，我是为了方便维护所以把 `style.css` 分离出来，它和 `screen.css` 都是整个博客的样式，合并打包之后是 `allinone.min.css`，所以要想生效，你把修改后的 `style.css` 与 `screen.css` 合并成为 `allinone.min.css` 就行
