### ISSUE TITLE
markdown有序列表，在页面上不显示？

### ISSUE THREAD

**Issue by shuyx** [xzhih/hexo-theme-casper#8]
markdown里面，写的有序列表，如+，-，*，最后在网页上，前面都是空白的，没有黑色小圆点显示，这是什么情况？

**Comment by xzhih** [comment]
有的啊，你看 https://zhih.me/hexo-casper-usage/

**Comment by shuyx** [comment]
你的我确实看得到啊，但我自己的就不行，不清楚为什么，很奇怪啊，比如你看：http://shuaimeng.ltd/2018/11/25/%E5%9C%A8Azure%E4%B8%8A%E6%90%AD%E5%BB%BAgit/

**Comment by xzhih** [comment]
我重新给整理了一下，现在应该是没问题了

另外也重新做了 `markdown` 的样式，启用 `hexo` 内置的代码高亮、行号，优化去顶部、去底部的动画，`toc` 点击跳转加入滚动，去除 `jquery`，优化请求文件个数减少 `http` 请求

**Comment by shuyx** [comment]
赞👍，markdown式样出现了，威武！
